[project]
name = "stacks-insurance-protocol"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/stacks-insurance-protocol/stacks-insurance-protocol/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.stacks-insurance-protocol]
path = "contracts/stacks-insurance-protocol.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
